// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_dto.proto

package com.hushow.demo.grpc.user.dto;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hushow.demo.grpc.user.dto.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.hushow.demo.grpc.user.dto.UserResponse user = 1;</code>
   */
  java.util.List<com.hushow.demo.grpc.user.dto.UserResponse> 
      getUserList();
  /**
   * <code>repeated .com.hushow.demo.grpc.user.dto.UserResponse user = 1;</code>
   */
  com.hushow.demo.grpc.user.dto.UserResponse getUser(int index);
  /**
   * <code>repeated .com.hushow.demo.grpc.user.dto.UserResponse user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .com.hushow.demo.grpc.user.dto.UserResponse user = 1;</code>
   */
  java.util.List<? extends com.hushow.demo.grpc.user.dto.UserResponseOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .com.hushow.demo.grpc.user.dto.UserResponse user = 1;</code>
   */
  com.hushow.demo.grpc.user.dto.UserResponseOrBuilder getUserOrBuilder(
      int index);
}
