// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_service.proto

package com.hushow.demo.grpc.user.service;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user_service.proto\022\035com.hushow.demo.gr" +
      "pc.user.dto\032\016user_dto.proto2\276\002\n\004User\022c\n\004" +
      "list\0220.com.hushow.demo.grpc.user.dto.Sea" +
      "rchUserRequest\032\'.com.hushow.demo.grpc.us" +
      "er.dto.UserList\"\000\022c\n\003add\022-.com.hushow.de" +
      "mo.grpc.user.dto.AddUserRequest\032+.com.hu" +
      "show.demo.grpc.user.dto.UserResponse\"\000\022l" +
      "\n\010addBatch\022-.com.hushow.demo.grpc.user.d" +
      "to.AddUserRequest\032+.com.hushow.demo.grpc" +
      ".user.dto.UserResponse\"\000(\0010\001B0\n!com.hush" +
      "ow.demo.grpc.user.serviceB\tUserProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.hushow.demo.grpc.user.dto.UserDto.getDescriptor(),
        });
    com.hushow.demo.grpc.user.dto.UserDto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
